name: 'Create Playdate Release'
description: 'Compiles a Playdate project and attaches it to a release'

branding:
  color: yellow
  icon: paperclip

inputs:
  github_token:
    description: 'You need to pass your GITHUB_TOKEN to the action'
    required: true

  # pdc options
  input:
    description: 'The source directory of the project'
    default: 'source'
    required: false
  output:
    description: 'The name of the build target directory'
    default: 'build'
    required: false
  compress:
    description: 'Compress output files'
    default: 'true'
    required: false
  quiet:
    description: 'Quiet mode, suppresses non-error output'
    default: 'false'
    required: false
  strip:
    description: 'Strip debug symbols from build'
    default: 'true'
    required: false
  verbose:
    description: 'Enables verbose mode'
    default: 'true'
    required: false

  # zip options
  include_files:
    description: 'List space-separated of files to include in the release'
    default: ''
    required: false

  # release options
  is_draft:
    description: 'Mark release is a draft'
    default: 'false'
    required: false
  is_prerelease:
    description: 'Mark release is a prerelease'
    default: 'false'
    required: false
  dry_run:
    description: 'Skips creation of a release'
    default: 'false'
    required: false

runs:
  using: "composite"
  steps:
    - name: Install SDK
      uses: idleberg/setup-playdate-sdk@v2.0.1

    - name: Build Project
      shell: bash
      run: |
        pdc_args=""
        pdc_args+=" ${{ inputs.compress == 'false' && '--no-compress' || '' }}"
        pdc_args+=" ${{ inputs.quiet == 'true' && '--quiet' || '' }}"
        pdc_args+=" ${{ inputs.strip == 'true' && '--strip' || '' }}"
        pdc_args+=" ${{ inputs.verbose == 'true' && inputs.quiet != 'true' && '--verbose' || '' }}"
        pdc_args+=" ${{ inputs.input }}"
        pdc_args+=" ${{ inputs.output }}.pdx"
        pdc $pdc_args;

        zip_args="-r -9"
        zip_args+=" ${{ inputs.output }}-${{ github.ref_name }}.zip"
        zip_args+=" ${{ inputs.output }}.pdx"
        zip_args+=" ${{ inputs.include_files }}"
        zip $zip_args;

    - name: Create Release
      uses: actions/create-release@v1
      id: create_release
      if: ${{ inputs.dry_run == 'false' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: ${{ github.ref_name }}
        draft: ${{ inputs.is_draft }}
        prerelease: ${{ inputs.is_prerelease }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      if: ${{ inputs.dry_run == 'false' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./${{ inputs.output }}-${{ github.ref_name }}.zip
        asset_name: ${{ inputs.output }}-${{ github.ref_name }}.zip
        asset_content_type: application/zip
