
name: test:include_files

on:
  push

jobs:
  test-run:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: idleberg/create-playdate-release@main
      with:
        dry_run: true
        input: .github/source
        include_files: 'LICENSE README.md'
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Included file exists
      run: |
        if ! ls build.pdx/main.pdz 1> /dev/null 2>&1; then
            echo "Build output doesn't exist"
            exit 1
        fi

        if ! unzip -l build-${{ github.ref_name }}.zip | grep LICENSE 1> /dev/null 2>&1; then
            echo "LICENSE doesn't exist"
            exit 1
        fi

        if ! unzip -l build-${{ github.ref_name }}.zip | grep README.md 1> /dev/null 2>&1; then
            echo "README.md doesn't exist"
            exit 1
        fi
