
name: test:compress

on:
  push

jobs:
  test-run:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - uses: idleberg/create-playdate-release@develop
      with:
        dry_run: true
        input: .github/source
        output: uncompressed
        compress: false
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - uses: idleberg/create-playdate-release@develop
      with:
        dry_run: true
        input: .github/source
        output: compressed
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build outputs have different file size
      run: |
        if ((`stat -c%s "uncompressed.pdx/main.pdz"` == `stat -c%s "compressed.pdx/main.pdz"`)); then
          echo "Both output files have the same size"
          exit 1
        fi
